### ISSUE TITLE
Converting English Math Problems to Alpha-Geometry and Drawing them

### ISSUE THREAD

**Issue by mostafamdy** [tpgh24/ag4masses#3]
Hi,

It's great work, thanks for it!

I just want to know if there is any method to convert a math problem written in English into Alpha-Geometry input format. Also, Can we use Alpha-Geometry to draw the problem?

**Comment by tpgh24** [comment]
I am not aware of a way to automatically convert problems in English to AlphaGeometry's problem format, but I have detailed description of the problem language in the README file of AG4Masses, I find it not very difficult to do once you understand the problem language.

Yes you can let AG draw a diagram by changing the conclusion of the problem to something trivial like `? cong a b a b`. For more tips, see the "Some Tips" section of the README file.

**Comment by mostafamdy** [comment]
Thanks
